theme： minima

title: Masami Nagasawa
author: Timo Zhang
email: thisismyemail@mail.com
description: > # this means to ignore newlines until "baseurl:"
        This is my blog. I love Masami!!

# social links
github_username: TimoLin 

show_excerpts: true # set to false to remove excerpts on the homepage
